config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :show, :create, :edit, :update ] do
    resources :doses, only: [ :new, :create ]
    resources :reviews, only: [ :create ]
  end
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :reviews, :dependent => :destroy
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: (0..5),
    message: "%{value} is not a valid rating" }
  validates :rating, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @review = Review.new
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/index'
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail = Cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Reviews.all
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="card mx-auto my-5" style="max-width: 700px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag "cocktail_form.jpg", alt: "Cocktails", class: 'card-img' %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Edit cocktail</h5>
          <%= simple_form_for(@cocktail) do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :photo, as: :file %>
            <%= f.submit class: "btn btn-primary" %>
          <% end %>
          <%= link_to 'Back to cocktail', cocktail_path(@cocktail), class: 'btn btn-dark mt-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="cocktails">
    <% @cocktails.each do |cocktail| %>
    <% if cocktail.photo.attached? %>
          <%= link_to cocktail_path(cocktail) do %>
            <div class="cocktail-card mt-5">
              <div class="cocktail-card-bg" style="background-image: linear-gradient(rgba(0,0,0,.4),rgba(0,0,0,.5)),url('<%= cl_image_path cocktail.photo.key, :quality=>"auto", :fetch_format=>:auto %>');">
                <%= cocktail.name %>
              </div>
            </div>
          <% end %>
      <% else %>
          <%= link_to cocktail_path(cocktail) do %>
            <div class="cocktail-card mt-5">
              <div class="cocktail-card-bg alt-img">
                <%= cocktail.name %>
              </div>
            </div>
          <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<% if @cocktail.photo.attached? %>
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url('<%= cl_image_path @cocktail.photo.key, :quality=>"auto", :fetch_format=>:auto %>');">
        <div class="container">
          <h1><%= @cocktail.name %></h1>
          <%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class: 'btn btn-primary mt-3 index' %>
        </div>
      </div>
    <% else %>
      <div class="banner alt-image">
        <div class="container">
          <h1><%= @cocktail.name %></h1>
          <%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class: 'btn btn-primary mt-3 index' %>
        </div>
      </div>
<% end %>

<div class="container">
  <div class="cocktails-infos my-5 d-flex justify-content-between align-items-start">
    <div class="cocktail-description">
      <h3 class="mb-3">Description</h3>
      <%= @cocktail.description %>
      <%= link_to "Edit cocktail", edit_cocktail_path(@cocktail), class: 'btn btn-primary mt-3' %>
    </div>
    <div class="cocktails-ingredients">
      <h3 class="mb-3">Ingredients</h3>
      <% @cocktail.doses.each do |dose| %>
        <div class="div">
          <%= dose.ingredient.name.capitalize %> -
          <span class="text-muted"><%= dose.description %></span>
          <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
            <%= icon('far', 'trash-alt', class: 'px-2') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="cocktails-reviews mb-5">
    <h3 class="my-5">Reviews</h3>
    <ul>
      <% @cocktail.reviews.each do |review| %>
        <li class="d-flex justify-content-between align-items-start">
          <p><%= review.content %></p>
          <p class="text-primary"><%= review.rating %> Star(s)</p>
        </li>
      <% end %>
    </ul>
  </div>
  <hr>
  <div class="reviews-card">
    <h3>Add a review</h3>
    <%= render "reviews/form", cocktail: @cocktail, review: @review %>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [ cocktail, dose ] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Add dose", class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<div class="container">
  <div class="card mx-auto my-5" style="max-width: 700px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag "cocktail_form.jpg", alt: "Cocktails", class: 'card-img' %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Add a dose to <%= @cocktail.name %></h5>
          <%= render "form", cocktail: @cocktail, dose: @dose %>
          <%= link_to 'Back to cocktail', cocktail_path(@cocktail), class: 'btn btn-dark mt-3' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h4>Cocktails Club</h4>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", cocktails_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addCocktailModal">
          New cocktail
        </button>
      </li>
    </ul>
  </div>
</div>

<!-- New Cocktail Modal -->
<div class="modal fade" id="addCocktailModal" tabindex="-1" aria-labelledby="addCocktailModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

        <h5 class="modal-title" id="addCocktailModalLabel">Add a cocktail</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <%= simple_form_for(@cocktail, remote: true) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless controller.controller_name == "pages" && controller.action_name == "home" %>
      <%= render "layouts/navbar" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="hero">
  <h1 class="mt-5">Cocktail Club</h1>
  <%= link_to 'Discover', cocktails_path, class: 'mb-5' %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [ cocktail, review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>